version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore ./Trouvaille.sln
build:
  project: ./Trouvaille.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: EWBYUtWGL5oFuheYDhvvaAFShvSF55qRG
after_test: 
  - Trouvaille\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[*]*" -target:"Trouvaille\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single Trouvaille.UnitTests\bin\Debug\Trouvaille.UnitTests.dll" -output:cover.xml
  - Trouvaille\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml